import type { Defect } from '../types';

// Mock users for assignment
const mockUsers = [
  { id: 'user-1', name: 'John Smith' },
  { id: 'user-2', name: 'Sarah Johnson' },
  { id: 'user-3', name: 'David Lee' },
  { id: 'user-4', name: 'Mike Davis' },
  { id: 'user-5', name: 'Emma Wilson' },
  { id: 'user-6', name: 'Lisa Anderson' },
];

// Asset names mapping
const assetNames: Record<string, string> = {
  'AST-000001': 'Excavator',
  'AST-000002': 'MEWP',
  'AST-000003': 'Crane',
  'AST-000004': 'Forklift',
  'AST-000005': 'Generator',
  'AST-000006': 'Compressor',
  'AST-000008': 'Pump',
};

// Initial seed data - 10 defects
export const initialSeedDefects: Defect[] = [
  {
    id: 'def-1',
    defectCode: 'DEF-0001',
    title: 'Hydraulic leak at boom base',
    description: 'Significant hydraulic fluid leak detected at the boom base connection. Requires immediate attention to prevent further damage and potential safety hazard.',
    status: 'Open',
    severityModel: 'LMH',
    severity: 'High',
    unsafeDoNotUse: true,
    assetId: 'AST-000002',
    assignedToId: 'user-1',
    assignedToName: 'John Smith',
    createdAt: '2025-12-14T09:00:00Z',
    targetRectificationDate: '2025-12-16',
    updatedAt: '2025-12-14T09:00:00Z',
    createdBy: 'user-1',
    createdByName: 'John Smith',
    updatedBy: 'user-1',
    updatedByName: 'John Smith',
    siteId: '1',
    siteName: 'Site A',
    reopenedCount: 0,
    actions: [],
    attachments: [],
    beforeAfterRequired: false,
    complianceTags: [],
    history: [],
    comments: [],
  },
  {
    id: 'def-2',
    defectCode: 'DEF-0002',
    title: 'Air filter requires replacement',
    description: 'Air filter showing signs of excessive wear and reduced efficiency. Should be replaced during next maintenance window.',
    status: 'Open',
    severityModel: 'LMH',
    severity: 'Medium',
    unsafeDoNotUse: false,
    assetId: 'AST-000006',
    assignedToId: 'user-2',
    assignedToName: 'Sarah Johnson',
    createdAt: '2025-12-15T10:30:00Z',
    targetRectificationDate: '2025-12-20',
    updatedAt: '2025-12-15T10:30:00Z',
    createdBy: 'user-2',
    createdByName: 'Sarah Johnson',
    updatedBy: 'user-2',
    updatedByName: 'Sarah Johnson',
    siteId: '1',
    siteName: 'Site A',
    reopenedCount: 0,
    actions: [],
    attachments: [],
    beforeAfterRequired: false,
    complianceTags: [],
    history: [],
    comments: [],
  },
  {
    id: 'def-3',
    defectCode: 'DEF-0003',
    title: 'Emergency stop intermittent',
    description: 'Emergency stop button showing intermittent operation. Safety critical - equipment must not be used until resolved.',
    status: 'Overdue',
    severityModel: 'LMH',
    severity: 'High',
    unsafeDoNotUse: true,
    assetId: 'AST-000003',
    assignedToId: 'user-3',
    assignedToName: 'David Lee',
    createdAt: '2025-12-10T14:00:00Z',
    targetRectificationDate: '2025-12-12',
    updatedAt: '2025-12-10T14:00:00Z',
    createdBy: 'user-3',
    createdByName: 'David Lee',
    updatedBy: 'user-3',
    updatedByName: 'David Lee',
    siteId: '2',
    siteName: 'Site B',
    reopenedCount: 0,
    actions: [],
    attachments: [],
    beforeAfterRequired: true,
    complianceTags: ['PUWER'],
    history: [],
    comments: [],
  },
  {
    id: 'def-4',
    defectCode: 'DEF-0004',
    title: 'Control panel LED indicator faulty',
    description: 'One of the LED indicators on the control panel is not illuminating correctly. Non-critical but should be addressed.',
    status: 'Open',
    severityModel: 'LMH',
    severity: 'Low',
    unsafeDoNotUse: false,
    assetId: 'AST-000005',
    assignedToId: 'user-4',
    assignedToName: 'Mike Davis',
    createdAt: '2025-12-14T11:15:00Z',
    targetRectificationDate: '2025-12-22',
    updatedAt: '2025-12-14T11:15:00Z',
    createdBy: 'user-4',
    createdByName: 'Mike Davis',
    updatedBy: 'user-4',
    updatedByName: 'Mike Davis',
    siteId: '1',
    siteName: 'Site A',
    reopenedCount: 0,
    actions: [],
    attachments: [],
    beforeAfterRequired: false,
    complianceTags: [],
    history: [],
    comments: [],
  },
  {
    id: 'def-5',
    defectCode: 'DEF-0005',
    title: 'Guardrail missing section',
    description: 'One section of the guardrail has been removed and not replaced. Safety concern for operators.',
    status: 'Closed',
    severityModel: 'LMH',
    severity: 'Medium',
    unsafeDoNotUse: false,
    assetId: 'AST-000001',
    assignedToId: 'user-5',
    assignedToName: 'Emma Wilson',
    createdAt: '2025-12-11T08:00:00Z',
    targetRectificationDate: '2025-12-15',
    updatedAt: '2025-12-15T16:00:00Z',
    createdBy: 'user-5',
    createdByName: 'Emma Wilson',
    updatedBy: 'user-5',
    updatedByName: 'Emma Wilson',
    siteId: '1',
    siteName: 'Site A',
    reopenedCount: 0,
    actions: [],
    attachments: [],
    beforeAfterRequired: false,
    complianceTags: ['PUWER'],
    history: [],
    comments: [],
  },
  {
    id: 'def-6',
    defectCode: 'DEF-0006',
    title: 'Mast chain tension excessive',
    description: 'Mast chain tension is outside recommended parameters. Requires adjustment to prevent premature wear.',
    status: 'Open',
    severityModel: 'LMH',
    severity: 'High',
    unsafeDoNotUse: true,
    assetId: 'AST-000004',
    assignedToId: 'user-6',
    assignedToName: 'Lisa Anderson',
    createdAt: '2025-12-13T13:45:00Z',
    targetRectificationDate: '2025-12-14',
    updatedAt: '2025-12-13T13:45:00Z',
    createdBy: 'user-6',
    createdByName: 'Lisa Anderson',
    updatedBy: 'user-6',
    updatedByName: 'Lisa Anderson',
    siteId: '3',
    siteName: 'Site C',
    reopenedCount: 0,
    actions: [],
    attachments: [],
    beforeAfterRequired: false,
    complianceTags: [],
    history: [],
    comments: [],
  },
  {
    id: 'def-7',
    defectCode: 'DEF-0007',
    title: 'Pump seal showing signs of wear',
    description: 'Pump seal beginning to show signs of wear. Should be monitored and replaced during next scheduled maintenance.',
    status: 'Overdue',
    severityModel: 'LMH',
    severity: 'Medium',
    unsafeDoNotUse: false,
    assetId: 'AST-000008',
    assignedToId: 'user-1',
    assignedToName: 'John Smith',
    createdAt: '2025-12-09T09:30:00Z',
    targetRectificationDate: '2025-12-11',
    updatedAt: '2025-12-09T09:30:00Z',
    createdBy: 'user-1',
    createdByName: 'John Smith',
    updatedBy: 'user-1',
    updatedByName: 'John Smith',
    siteId: '2',
    siteName: 'Site B',
    reopenedCount: 0,
    actions: [],
    attachments: [],
    beforeAfterRequired: false,
    complianceTags: [],
    history: [],
    comments: [],
  },
  {
    id: 'def-8',
    defectCode: 'DEF-0008',
    title: 'Battery terminal corrosion',
    description: 'Minor corrosion detected on battery terminals. Clean and apply protective coating recommended.',
    status: 'Open',
    severityModel: 'LMH',
    severity: 'Low',
    unsafeDoNotUse: false,
    assetId: 'AST-000002',
    assignedToId: 'user-4',
    assignedToName: 'Mike Davis',
    createdAt: '2025-12-15T10:00:00Z',
    targetRectificationDate: '2025-12-25',
    updatedAt: '2025-12-15T10:00:00Z',
    createdBy: 'user-4',
    createdByName: 'Mike Davis',
    updatedBy: 'user-4',
    updatedByName: 'Mike Davis',
    siteId: '1',
    siteName: 'Site A',
    reopenedCount: 0,
    actions: [],
    attachments: [],
    beforeAfterRequired: false,
    complianceTags: [],
    history: [],
    comments: [],
  },
  {
    id: 'def-9',
    defectCode: 'DEF-0009',
    title: 'Pressure relief valve not operating',
    description: 'Pressure relief valve failed to activate during test. Critical safety component - equipment quarantined.',
    status: 'Closed',
    severityModel: 'LMH',
    severity: 'High',
    unsafeDoNotUse: true,
    assetId: 'AST-000006',
    assignedToId: 'user-2',
    assignedToName: 'Sarah Johnson',
    createdAt: '2025-12-08T07:00:00Z',
    targetRectificationDate: '2025-12-10',
    updatedAt: '2025-12-10T15:30:00Z',
    createdBy: 'user-2',
    createdByName: 'Sarah Johnson',
    updatedBy: 'user-2',
    updatedByName: 'Sarah Johnson',
    siteId: '1',
    siteName: 'Site A',
    reopenedCount: 0,
    actions: [],
    attachments: [],
    beforeAfterRequired: true,
    complianceTags: ['PUWER'],
    history: [],
    comments: [],
  },
  {
    id: 'def-10',
    defectCode: 'DEF-0010',
    title: 'Wire rope fraying detected',
    description: 'Minor fraying detected on wire rope. Monitor closely and replace if condition deteriorates.',
    status: 'Open',
    severityModel: 'LMH',
    severity: 'Medium',
    unsafeDoNotUse: false,
    assetId: 'AST-000003',
    assignedToId: 'user-3',
    assignedToName: 'David Lee',
    createdAt: '2025-12-16T12:00:00Z',
    targetRectificationDate: '2025-12-21',
    updatedAt: '2025-12-16T12:00:00Z',
    createdBy: 'user-3',
    createdByName: 'David Lee',
    updatedBy: 'user-3',
    updatedByName: 'David Lee',
    siteId: '2',
    siteName: 'Site B',
    reopenedCount: 0,
    actions: [],
    attachments: [],
    beforeAfterRequired: false,
    complianceTags: ['LOLER'],
    history: [],
    comments: [],
  },
];

// Helper to get next defect code
export function getNextDefectCode(defects: Defect[]): string {
  const codes = defects.map(d => d.defectCode);
  const numbers = codes
    .map(code => {
      const match = code.match(/DEF-(\d+)/);
      return match ? parseInt(match[1], 10) : 0;
    })
    .filter(n => n > 0);
  const maxNum = numbers.length > 0 ? Math.max(...numbers) : 0;
  return `DEF-${String(maxNum + 1).padStart(4, '0')}`;
}

// Helper to get random asset
export function getRandomAsset(): string {
  const assets = Object.keys(assetNames);
  return assets[Math.floor(Math.random() * assets.length)];
}

// Helper to get random user
export function getRandomUser(): { id: string; name: string } {
  return mockUsers[Math.floor(Math.random() * mockUsers.length)];
}

// Helper to get random severity
export function getRandomSeverity(): 'Low' | 'Medium' | 'High' {
  const severities: ('Low' | 'Medium' | 'High')[] = ['Low', 'Medium', 'High'];
  return severities[Math.floor(Math.random() * severities.length)];
}


